table_name: patients
main_dttm_col: birth_date
description: null
default_endpoint: null
offset: 0
cache_timeout: null
schema: null
sql: select * from patient_flat
params: null
template_params: null
filter_select_enabled: true
fetch_values_predicate: null
extra: null
normalize_columns: false
always_filter_main_dttm: false
uuid: d12188bd-6f8c-424d-8c13-b4e8e34d73e1
metrics:
- metric_name: count
  verbose_name: COUNT(*)
  metric_type: count
  expression: COUNT(*)
  description: null
  d3format: null
  currency: null
  extra:
    warning_markdown: ''
  warning_text: null
columns:
- column_name: is_deceased
  verbose_name: null
  is_dttm: false
  is_active: true
  type: BOOLEAN
  advanced_data_type: null
  groupby: true
  filterable: true
  expression: null
  description: null
  python_date_format: null
  extra: {}
- column_name: active
  verbose_name: null
  is_dttm: false
  is_active: true
  type: BOOLEAN
  advanced_data_type: null
  groupby: true
  filterable: true
  expression: null
  description: null
  python_date_format: null
  extra: {}
- column_name: deceased_time
  verbose_name: null
  is_dttm: true
  is_active: true
  type: DATETIMETZ
  advanced_data_type: null
  groupby: true
  filterable: true
  expression: null
  description: null
  python_date_format: null
  extra: {}
- column_name: birth_date
  verbose_name: null
  is_dttm: true
  is_active: true
  type: DATE
  advanced_data_type: null
  groupby: true
  filterable: true
  expression: null
  description: null
  python_date_format: null
  extra: {}
- column_name: facility_org_id
  verbose_name: null
  is_dttm: false
  is_active: true
  type: STRING
  advanced_data_type: null
  groupby: true
  filterable: true
  expression: null
  description: null
  python_date_format: null
  extra: {}
- column_name: facility_name
  verbose_name: null
  is_dttm: false
  is_active: true
  type: STRING
  advanced_data_type: null
  groupby: true
  filterable: true
  expression: null
  description: null
  python_date_format: null
  extra: {}
- column_name: organization_id
  verbose_name: null
  is_dttm: false
  is_active: true
  type: STRING
  advanced_data_type: null
  groupby: true
  filterable: true
  expression: null
  description: null
  python_date_format: null
  extra: {}
- column_name: practitioner_id
  verbose_name: null
  is_dttm: false
  is_active: true
  type: STRING
  advanced_data_type: null
  groupby: true
  filterable: true
  expression: null
  description: null
  python_date_format: null
  extra: {}
- column_name: family
  verbose_name: null
  is_dttm: false
  is_active: true
  type: STRING
  advanced_data_type: null
  groupby: true
  filterable: true
  expression: null
  description: null
  python_date_format: null
  extra: {}
- column_name: gender
  verbose_name: null
  is_dttm: false
  is_active: true
  type: STRING
  advanced_data_type: null
  groupby: true
  filterable: true
  expression: null
  description: null
  python_date_format: null
  extra: {}
- column_name: id
  verbose_name: null
  is_dttm: false
  is_active: true
  type: STRING
  advanced_data_type: null
  groupby: true
  filterable: true
  expression: null
  description: null
  python_date_format: null
  extra: {}
- column_name: given
  verbose_name: null
  is_dttm: false
  is_active: true
  type: STRING
  advanced_data_type: null
  groupby: true
  filterable: true
  expression: null
  description: null
  python_date_format: null
  extra: {}
version: 1.0.0
database_uuid: 4e5f4045-a62d-4964-b719-58229a60e7fe
