table_name: stock
main_dttm_col: null
description: null
default_endpoint: null
offset: 0
cache_timeout: null
schema: null
sql: "SELECT product_id,\n       product.name -> 'en_US' AS product_name,\n      \
  \                 quantity,\n                       complete_name AS warehouse,\n\
  \                       company.name AS facility\nFROM stock_quant AS stock\nJOIN\
  \ product_template AS product ON stock.product_id = product.id\nJOIN stock_location\
  \ AS LOCATION ON stock.location_id = location.id\nJOIN res_company AS company ON\
  \ location.company_id = company.id"
params: null
template_params: null
filter_select_enabled: true
fetch_values_predicate: null
extra: null
normalize_columns: false
always_filter_main_dttm: false
uuid: be4fbdb0-f25b-48b1-9c89-5cd75427527e
metrics:
- metric_name: count
  verbose_name: COUNT(*)
  metric_type: count
  expression: COUNT(*)
  description: null
  d3format: null
  currency: null
  extra: null
  warning_text: null
columns:
- column_name: quantity
  verbose_name: null
  is_dttm: false
  is_active: true
  type: DECIMAL
  advanced_data_type: null
  groupby: true
  filterable: true
  expression: null
  description: null
  python_date_format: null
  extra: null
- column_name: product_name
  verbose_name: null
  is_dttm: false
  is_active: true
  type: JSONB
  advanced_data_type: null
  groupby: true
  filterable: true
  expression: null
  description: null
  python_date_format: null
  extra: null
- column_name: product_id
  verbose_name: null
  is_dttm: false
  is_active: true
  type: INTEGER
  advanced_data_type: null
  groupby: true
  filterable: true
  expression: null
  description: null
  python_date_format: null
  extra: null
- column_name: facility
  verbose_name: null
  is_dttm: false
  is_active: true
  type: STRING
  advanced_data_type: null
  groupby: true
  filterable: true
  expression: null
  description: null
  python_date_format: null
  extra: null
- column_name: warehouse
  verbose_name: null
  is_dttm: false
  is_active: true
  type: STRING
  advanced_data_type: null
  groupby: true
  filterable: true
  expression: null
  description: null
  python_date_format: null
  extra: null
version: 1.0.0
database_uuid: 0d454a0e-f97e-4bf5-9b8b-c03c78d76b2e
