services:
  env-substitution:
    environment:
      - OPENELIS_PUBLIC_URL_1=${OPENELIS_PUBLIC_URL_1}
      - OPENELIS_HOSTNAME_1=${OPENELIS_HOSTNAME_1}
      - OPENELIS_PUBLIC_URL_2=${OPENELIS_PUBLIC_URL_2}
      - OPENELIS_HOSTNAME_2=${OPENELIS_HOSTNAME_2}
      - SERVER_SCHEME=${SERVER_SCHEME}
      - KEYCLOAK_PUBLIC_URL=${SERVER_SCHEME}://${KEYCLOAK_HOSTNAME}
      - ACCESSION_NUMBER_PREFIX=${ACCESSION_NUMBER_PREFIX}

  fhir.openelis.org:
    image: itechuw/openelis-global-2-fhir:3.2.1.8

  frontend.openelis.org:
    image: itechuw/openelis-global-2-frontend:3.2.1.8

  oe.openelis.org:
    image: itechuw/openelis-global-2:3.2.1.8
    environment:
      DEFAULT_PW: ${OPENELIS_DEFAULT_PASSWORD}
      TZ: ${TZ:-UTC}
      CATALINA_OPTS: "-Ddatasource.url=jdbc:postgresql://${OPENELIS_DB_HOST}:5432/${OPENELIS_DB_NAME} -Ddatasource.username=${OPENELIS_DB_USER} -Ddatasource.password=${OPENELIS_DB_PASSWORD} -Doe.ssl.truststorepath=${SSL_TRUSTSTORE_PATH} -Doe.ssl.truststorepassword=${SSL_TRUSTSTORE_PASSWORD} -Doe.ssl.keystorepath=${SSL_KEYSTORE_PATH} -Doe.ssl.keystorepassword=${SSL_KEYSTORE_PASSWORD}"
      SSL_KEYSTORE_PATH: ${SSL_KEYSTORE_PATH}
      SSL_KEYSTORE_PASSWORD: ${SSL_KEYSTORE_PASSWORD}
      SSL_TRUSTSTORE_PATH: ${SSL_TRUSTSTORE_PATH}
      SSL_TRUSTSTORE_PASSWORD: ${SSL_TRUSTSTORE_PASSWORD}
      OEG_FACILITY_ID: ${OEG_FACILITY_ID}
      OPENELIS_FHIR_STORE_URL: ${OPENELIS_FHIR_STORE_URL}
      OPENELIS_ANALYZER_BRIDGE_URL: ${OPENELIS_ANALYZER_BRIDGE_URL:-https://oe-analyzer-bridge:8443}
    volumes:
      - "${OPENELIS_TRUST_STORE:-key_trust-store-volume}:/etc/openelis-global"
      - "${OPENELIS_CONFIG_PATH}/plugins/:/var/lib/openelis-global/plugins"
      - "${OPENELIS_CONFIG_PATH}/properties/SystemConfiguration.properties:/var/lib/openelis-global/properties/SystemConfiguration.properties"
      - "${OPENELIS_CONFIG_PATH}/analyzer/analyzer-test-map.csv:/var/lib/openelis-global/analyzer/analyzer-test-map.csv"
      - "${OPENELIS_CONFIG_PATH}/odoo/odoo-test-product-mapping.csv:/var/lib/openelis-global/odoo/odoo-test-product-mapping.csv"
      - "${OPENELIS_CONFIG_PATH}/ocl:/var/lib/openelis-global/ocl"
      - "${OPENELIS_CONFIG_PATH}/programs/:/var/lib/openelis-global/programs"
      - "${OPENELIS_CONFIG_PATH}/configuration:/var/lib/openelis-global/configuration"
      - "${OPENELIS_CONFIG_PATH}/menu/menu_config.json:/var/lib/openelis-global/menu/menu_config.json"
      - "${OPENELIS_CONFIG_PATH}/analyzer-profiles:/data/analyzer-profiles:ro"
      - "${OPENELIS_LUCENE_INDEX:-lucene_index-vol}:/var/lib/lucene_index"
      - "${OPENELIS_ANALYZER_DROPS_MOUNT_PATH:-${OPENELIS_CONFIG_PATH}/analyzer-drops}:/data/analyzer-drops:ro"
      - analyzer-imports:/data/analyzer-imports
