parent=keycloak.v2

darkMode=false

styles=css/styles.css vendor/patternfly-v5/patternfly.min.css vendor/patternfly-v5/patternfly-addons.css css/branding.css

poweredByLogos=ozone-logo.png:Ozone, openelis-logo.png:OpenELIS, odoo-logo.svg:Odoo, keycloak-logo.svg:Keycloak, superset-logo-small.png:Superset
